<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Add32DoctorSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 15,
                'name' => 'Dr. Lê Văn Minh',
                'email' => 'doctor9@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Hà Nội',
                'phone' => '0909000009',
                'avatar' => 'https://i.pravatar.cc/300?img=15',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'Dr. Phạm Thùy Linh',
                'email' => 'doctor10@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Hồ Chí Minh',
                'phone' => '0909000010',
                'avatar' => 'https://i.pravatar.cc/300?img=16',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'Dr. Hoàng Đức Anh',
                'email' => 'doctor11@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Đà Nẵng',
                'phone' => '0909000011',
                'avatar' => 'https://i.pravatar.cc/300?img=17',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'Dr. Trần Mai Phương',
                'email' => 'doctor12@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Hải Phòng',
                'phone' => '0909000012',
                'avatar' => 'https://i.pravatar.cc/300?img=18',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'name' => 'Dr. Vũ Mạnh Cường',
                'email' => 'doctor13@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Cần Thơ',
                'phone' => '0909000013',
                'avatar' => 'https://i.pravatar.cc/300?img=19',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'Dr. Nguyễn Thu Hà',
                'email' => 'doctor14@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Nha Trang',
                'phone' => '0909000014',
                'avatar' => 'https://i.pravatar.cc/300?img=20',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'name' => 'Dr. Đặng Quốc Bảo',
                'email' => 'doctor15@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Huế',
                'phone' => '0909000015',
                'avatar' => 'https://i.pravatar.cc/300?img=21',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'name' => 'Dr. Lý Thanh Tú',
                'email' => 'doctor16@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Vũng Tàu',
                'phone' => '0909000016',
                'avatar' => 'https://i.pravatar.cc/300?img=22',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'name' => 'Dr. Bùi Anh Tuấn',
                'email' => 'doctor17@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Hạ Long',
                'phone' => '0909000017',
                'avatar' => 'https://i.pravatar.cc/300?img=23',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'name' => 'Dr. Đỗ Ngọc Ánh',
                'email' => 'doctor18@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Phú Quốc',
                'phone' => '0909000018',
                'avatar' => 'https://i.pravatar.cc/300?img=24',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'name' => 'Dr. Hồ Sỹ Hùng',
                'email' => 'doctor19@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Buôn Ma Thuột',
                'phone' => '0909000019',
                'avatar' => 'https://i.pravatar.cc/300?img=25',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'name' => 'Dr. Phan Thảo Nguyên',
                'email' => 'doctor20@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Đà Lạt',
                'phone' => '0909000020',
                'avatar' => 'https://i.pravatar.cc/300?img=26',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'name' => 'Dr. Trịnh Đình Khôi',
                'email' => 'doctor21@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Quy Nhơn',
                'phone' => '0909000021',
                'avatar' => 'https://i.pravatar.cc/300?img=27',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'name' => 'Dr. Võ Thị Mỹ Dung',
                'email' => 'doctor22@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Long Xuyên',
                'phone' => '0909000022',
                'avatar' => 'https://i.pravatar.cc/300?img=28',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'name' => 'Dr. Đào Xuân Trường',
                'email' => 'doctor23@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Rạch Giá',
                'phone' => '0909000023',
                'avatar' => 'https://i.pravatar.cc/300?img=29',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'name' => 'Dr. Lâm Thanh Trúc',
                'email' => 'doctor24@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Cà Mau',
                'phone' => '0909000024',
                'avatar' => 'https://i.pravatar.cc/300?img=30',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'name' => 'Dr. Ngô Gia Bảo',
                'email' => 'doctor25@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Thái Bình',
                'phone' => '0909000025',
                'avatar' => 'https://i.pravatar.cc/300?img=31',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'name' => 'Dr. Dương Kim Oanh',
                'email' => 'doctor26@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Nam Định',
                'phone' => '0909000026',
                'avatar' => 'https://i.pravatar.cc/300?img=32',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'name' => 'Dr. Huỳnh Văn Thắng',
                'email' => 'doctor27@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Bến Tre',
                'phone' => '0909000027',
                'avatar' => 'https://i.pravatar.cc/300?img=33',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 34,
                'name' => 'Dr. Tống Bích Vân',
                'email' => 'doctor28@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Vĩnh Long',
                'phone' => '0909000028',
                'avatar' => 'https://i.pravatar.cc/300?img=34',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 35,
                'name' => 'Dr. Vương Minh Đức',
                'email' => 'doctor29@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Bắc Ninh',
                'phone' => '0909000029',
                'avatar' => 'https://i.pravatar.cc/300?img=35',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 36,
                'name' => 'Dr. Đinh Hồng Nhung',
                'email' => 'doctor30@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Hà Tĩnh',
                'phone' => '0909000030',
                'avatar' => 'https://i.pravatar.cc/300?img=36',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'name' => 'Dr. Trần Quốc Việt',
                'email' => 'doctor31@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Ninh Bình',
                'phone' => '0909000031',
                'avatar' => 'https://i.pravatar.cc/300?img=37',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'name' => 'Dr. Lê Thị Bích Hạnh',
                'email' => 'doctor32@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Thanh Hóa',
                'phone' => '0909000032',
                'avatar' => 'https://i.pravatar.cc/300?img=38',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'name' => 'Dr. Phùng Hữu Lộc',
                'email' => 'doctor33@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Hòa Bình',
                'phone' => '0909000033',
                'avatar' => 'https://i.pravatar.cc/300?img=39',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'name' => 'Dr. Hoàng Thị Minh Châu',
                'email' => 'doctor34@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Sơn La',
                'phone' => '0909000034',
                'avatar' => 'https://i.pravatar.cc/300?img=40',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'name' => 'Dr. Nguyễn Đình Sang',
                'email' => 'doctor35@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Lai Châu',
                'phone' => '0909000035',
                'avatar' => 'https://i.pravatar.cc/300?img=41',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'name' => 'Dr. Vũ Thị Hương Giang',
                'email' => 'doctor36@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Cao Bằng',
                'phone' => '0909000036',
                'avatar' => 'https://i.pravatar.cc/300?img=42',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'name' => 'Dr. Đỗ Trung Hiếu',
                'email' => 'doctor37@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Lạng Sơn',
                'phone' => '0909000037',
                'avatar' => 'https://i.pravatar.cc/300?img=43',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'name' => 'Dr. Trần Thị Ngọc Huyền',
                'email' => 'doctor38@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Tuyên Quang',
                'phone' => '0909000038',
                'avatar' => 'https://i.pravatar.cc/300?img=44',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'name' => 'Dr. Lương Xuân Trường',
                'email' => 'doctor39@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Yên Bái',
                'phone' => '0909000039',
                'avatar' => 'https://i.pravatar.cc/300?img=45',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'name' => 'Dr. Nguyễn Thị Kiều Diễm',
                'email' => 'doctor40@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Quảng Ninh',
                'phone' => '0909000040',
                'avatar' => 'https://i.pravatar.cc/300?img=46',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'name' => 'vanced',
                'email' => 'vancedloile@gmail.com',
                'password' => '$2y$12$7sVqrl4xC8A1zJs74Hx.4efW7T9myKrMWoPQ4yGyFRPx7.ji8jL5W',
                'remember_token' => 'U23MzToALQFrSYQYy5rmiSuuJm3Pj1RWN2NoRI1IfoZPS8UQrR1ZQq0F3KRu',
                'address' => null,
                'phone' => null,
                'avatar' => 'https://lh3.googleusercontent.com/a/ACg8ocIPAc1RvoLkMjVORhyHjCyjT0taDE7cujcWnOJQQKx9vaH1c9E=s96-c',
                'gender' => 'Nam',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-12-02 17:27:27',
                'updated_at' => '2025-12-02 17:27:27',
                'deleted_at' => null,
            ],
        ]);

        DB::table('doctor_users')->insert([
            // Chuyên khoa Tim mạch (id: 1) - Bác sĩ 15-18
            [
                'id' => 10,
                'doctorId' => 15,
                'clinicId' => 1,
                'specializationId' => 1, // Tim mạch
                'phone' => '0909000009',
                'photo' => 'doctor9.jpg',
                'bio' => 'Bác sĩ chuyên khoa tim mạch với hơn 8 năm kinh nghiệm trong chẩn đoán và điều trị bệnh lý tim mạch. Chuyên về siêu âm tim và can thiệp tim mạch.',
                'experience_years' => 8,
                'certification' => 'Bác sĩ chuyên khoa II Tim mạch – Đại học Y Hà Nội, Chứng chỉ Siêu âm tim nâng cao',
                'date_of_birth' => '1984-06-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'doctorId' => 16,
                'clinicId' => 2,
                'specializationId' => 1, // Tim mạch
                'phone' => '0909000010',
                'photo' => 'doctor10.jpg',
                'bio' => 'Chuyên gia tim mạch với 10 năm kinh nghiệm, đặc biệt trong điều trị tăng huyết áp và suy tim. Từng tu nghiệp tại Singapore về điện sinh lý tim.',
                'experience_years' => 10,
                'certification' => 'Thạc sĩ Tim mạch – Đại học Y Dược TP.HCM, Chứng chỉ Điện sinh lý tim',
                'date_of_birth' => '1982-11-03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'doctorId' => 17,
                'clinicId' => 3,
                'specializationId' => 1, // Tim mạch
                'phone' => '0909000011',
                'photo' => 'doctor11.jpg',
                'bio' => 'Bác sĩ tim mạch chuyên về can thiệp mạch vành, đã thực hiện hơn 500 ca can thiệp. Đồng thời là giảng viên bộ môn Tim mạch.',
                'experience_years' => 12,
                'certification' => 'Tiến sĩ Y học – Chuyên ngành Tim mạch can thiệp, Đại học Y Dược Huế',
                'date_of_birth' => '1980-08-22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'doctorId' => 18,
                'clinicId' => 4,
                'specializationId' => 1, // Tim mạch
                'phone' => '0909000012',
                'photo' => 'doctor12.jpg',
                'bio' => 'Chuyên gia tim mạch nhi và người lớn, có kinh nghiệm trong điều trị bệnh tim bẩm sinh. Từng tham gia nhiều hội thảo quốc tế về tim mạch.',
                'experience_years' => 9,
                'certification' => 'Bác sĩ chuyên khoa I Tim mạch – Đại học Y Dược Cần Thơ, Chứng chỉ Tim mạch nhi',
                'date_of_birth' => '1983-02-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Chuyên khoa Da liễu (id: 2) - Bác sĩ 19-22
            [
                'id' => 14,
                'doctorId' => 19,
                'clinicId' => 5,
                'specializationId' => 2, // Da liễu
                'phone' => '0909000013',
                'photo' => 'doctor13.jpg',
                'bio' => 'Bác sĩ da liễu chuyên điều trị mụn trứng cá và sẹo rỗ. Có kinh nghiệm trong các phương pháp trị liệu laser và công nghệ cao.',
                'experience_years' => 7,
                'certification' => 'Bác sĩ chuyên khoa I Da liễu – Đại học Y Hà Nội, Chứng chỉ Thẩm mỹ da laser',
                'date_of_birth' => '1985-09-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'doctorId' => 20,
                'clinicId' => 1,
                'specializationId' => 2, // Da liễu
                'phone' => '0909000014',
                'photo' => 'doctor14.jpg',
                'bio' => 'Chuyên gia da liễu thẩm mỹ với 11 năm kinh nghiệm. Từng tu nghiệp tại Hàn Quốc về công nghệ trẻ hóa da và điều trị nám.',
                'experience_years' => 11,
                'certification' => 'Thạc sĩ Da liễu – Đại học Y Dược TP.HCM, Chứng chỉ Da liễu thẩm mỹ Hàn Quốc',
                'date_of_birth' => '1981-04-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'doctorId' => 21,
                'clinicId' => 2,
                'specializationId' => 2, // Da liễu
                'phone' => '0909000015',
                'photo' => 'doctor15.jpg',
                'bio' => 'Bác sĩ chuyên khoa da liễu, đặc biệt trong điều trị các bệnh da mãn tính như vảy nến, chàm, lupus ban đỏ.',
                'experience_years' => 13,
                'certification' => 'Bác sĩ chuyên khoa II Da liễu – Đại học Y Dược Huế, Chứng chỉ Miễn dịch da liễu',
                'date_of_birth' => '1979-12-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'doctorId' => 22,
                'clinicId' => 3,
                'specializationId' => 2, // Da liễu
                'phone' => '0909000016',
                'photo' => 'doctor16.jpg',
                'bio' => 'Chuyên gia về da liễu nhi và phụ khoa da liễu. Có nhiều nghiên cứu về các bệnh da ở trẻ em và phụ nữ mang thai.',
                'experience_years' => 8,
                'certification' => 'Bác sĩ chuyên khoa I Da liễu – Đại học Y Dược Cần Thơ, Chứng chỉ Da liễu nhi',
                'date_of_birth' => '1984-07-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Chuyên khoa Nhi khoa (id: 3) - Bác sĩ 23-26
            [
                'id' => 18,
                'doctorId' => 23,
                'clinicId' => 4,
                'specializationId' => 3, // Nhi khoa
                'phone' => '0909000017',
                'photo' => 'doctor17.jpg',
                'bio' => 'Bác sĩ nhi khoa chuyên về hô hấp và dị ứng. Có kinh nghiệm điều trị hen suyễn, viêm phổi ở trẻ em.',
                'experience_years' => 9,
                'certification' => 'Bác sĩ chuyên khoa I Nhi – Đại học Y Hà Nội, Chứng chỉ Hô hấp nhi',
                'date_of_birth' => '1983-01-19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'doctorId' => 24,
                'clinicId' => 5,
                'specializationId' => 3, // Nhi khoa
                'phone' => '0909000018',
                'photo' => 'doctor18.jpg',
                'bio' => 'Chuyên gia nhi khoa với 14 năm kinh nghiệm, đặc biệt trong lĩnh vực tiêu hóa và dinh dưỡng trẻ em.',
                'experience_years' => 14,
                'certification' => 'Thạc sĩ Nhi khoa – Đại học Y Dược TP.HCM, Chứng chỉ Tiêu hóa nhi',
                'date_of_birth' => '1978-10-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'doctorId' => 25,
                'clinicId' => 1,
                'specializationId' => 3, // Nhi khoa
                'phone' => '0909000019',
                'photo' => 'doctor19.jpg',
                'bio' => 'Bác sĩ nhi khoa chuyên về tim mạch nhi và sơ sinh. Đã tham gia nhiều ca phẫu thuật tim bẩm sinh phức tạp.',
                'experience_years' => 11,
                'certification' => 'Bác sĩ chuyên khoa II Nhi – Đại học Y Dược Huế, Chứng chỉ Tim mạch nhi',
                'date_of_birth' => '1980-03-27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'doctorId' => 26,
                'clinicId' => 2,
                'specializationId' => 3, // Nhi khoa
                'phone' => '0909000020',
                'photo' => 'doctor20.jpg',
                'bio' => 'Chuyên gia về thần kinh nhi và phát triển trẻ em. Có nhiều năm kinh nghiệm chẩn đoán và điều trị tự kỷ, tăng động.',
                'experience_years' => 10,
                'certification' => 'Bác sĩ chuyên khoa I Nhi – Đại học Y Dược Cần Thơ, Chứng chỉ Thần kinh nhi',
                'date_of_birth' => '1982-06-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Chuyên khoa Tiêu hóa (id: 4) - Bác sĩ 27-30
            [
                'id' => 22,
                'doctorId' => 27,
                'clinicId' => 3,
                'specializationId' => 4, // Tiêu hóa
                'phone' => '0909000021',
                'photo' => 'doctor21.jpg',
                'bio' => 'Bác sĩ chuyên khoa tiêu hóa với 8 năm kinh nghiệm nội soi tiêu hóa. Chuyên về chẩn đoán sớm ung thư đường tiêu hóa.',
                'experience_years' => 8,
                'certification' => 'Bác sĩ chuyên khoa I Tiêu hóa – Đại học Y Hà Nội, Chứng chỉ Nội soi can thiệp',
                'date_of_birth' => '1984-12-03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'doctorId' => 28,
                'clinicId' => 4,
                'specializationId' => 4, // Tiêu hóa
                'phone' => '0909000022',
                'photo' => 'doctor22.jpg',
                'bio' => 'Chuyên gia tiêu hóa và gan mật. Từng tu nghiệp tại Nhật Bản về kỹ thuật nội soi tiên tiến và điều trị viêm gan.',
                'experience_years' => 12,
                'certification' => 'Thạc sĩ Tiêu hóa – Đại học Y Dược TP.HCM, Chứng chỉ Gan mật học',
                'date_of_birth' => '1980-05-22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'doctorId' => 29,
                'clinicId' => 5,
                'specializationId' => 4, // Tiêu hóa
                'phone' => '0909000023',
                'photo' => 'doctor23.jpg',
                'bio' => 'Bác sĩ tiêu hóa chuyên về bệnh lý đại tràng và rối loạn tiêu hóa chức năng. Có nhiều nghiên cứu về hệ vi sinh đường ruột.',
                'experience_years' => 10,
                'certification' => 'Bác sĩ chuyên khoa II Tiêu hóa – Đại học Y Dược Huế, Chứng chỉ Tiêu hóa chức năng',
                'date_of_birth' => '1982-08-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'doctorId' => 30,
                'clinicId' => 1,
                'specializationId' => 4, // Tiêu hóa
                'phone' => '0909000024',
                'photo' => 'doctor24.jpg',
                'bio' => 'Chuyên gia về tiêu hóa nhi và dinh dưỡng. Đặc biệt kinh nghiệm trong điều trị rối loạn tiêu hóa ở trẻ sơ sinh và trẻ nhỏ.',
                'experience_years' => 9,
                'certification' => 'Bác sĩ chuyên khoa I Tiêu hóa – Đại học Y Dược Cần Thơ, Chứng chỉ Tiêu hóa nhi',
                'date_of_birth' => '1983-11-29',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Chuyên khoa Sản phụ khoa (id: 5) - Bác sĩ 31-34
            [
                'id' => 26,
                'doctorId' => 31,
                'clinicId' => 2,
                'specializationId' => 5, // Sản phụ khoa
                'phone' => '0909000025',
                'photo' => 'doctor25.jpg',
                'bio' => 'Bác sĩ sản phụ khoa chuyên về hỗ trợ sinh sản và điều trị hiếm muộn. Có kinh nghiệm trong thụ tinh nhân tạo.',
                'experience_years' => 7,
                'certification' => 'Bác sĩ chuyên khoa I Sản phụ khoa – Đại học Y Hà Nội, Chứng chỉ Hỗ trợ sinh sản',
                'date_of_birth' => '1985-02-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'doctorId' => 32,
                'clinicId' => 3,
                'specializationId' => 5, // Sản phụ khoa
                'phone' => '0909000026',
                'photo' => 'doctor26.jpg',
                'bio' => 'Chuyên gia sản phụ khoa với 15 năm kinh nghiệm. Đặc biệt trong phẫu thuật phụ khoa nội soi và điều trị u xơ tử cung.',
                'experience_years' => 15,
                'certification' => 'Thạc sĩ Sản phụ khoa – Đại học Y Dược TP.HCM, Chứng chỉ Phẫu thuật nội soi',
                'date_of_birth' => '1977-07-09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'doctorId' => 33,
                'clinicId' => 4,
                'specializationId' => 5, // Sản phụ khoa
                'phone' => '0909000027',
                'photo' => 'doctor27.jpg',
                'bio' => 'Bác sĩ sản khoa chuyên về thai kỳ nguy cơ cao và sơ sinh. Từng thực hiện nhiều ca đỡ đẻ phức tạp thành công.',
                'experience_years' => 11,
                'certification' => 'Bác sĩ chuyên khoa II Sản phụ khoa – Đại học Y Dược Huế, Chứng chỉ Sản khoa nguy cơ cao',
                'date_of_birth' => '1981-04-03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'doctorId' => 34,
                'clinicId' => 5,
                'specializationId' => 5, // Sản phụ khoa
                'phone' => '0909000028',
                'photo' => 'doctor28.jpg',
                'bio' => 'Chuyên gia về nội tiết sinh sản và mãn kinh. Có nhiều năm kinh nghiệm điều trị rối loạn kinh nguyệt và mãn kinh.',
                'experience_years' => 13,
                'certification' => 'Bác sĩ chuyên khoa I Sản phụ khoa – Đại học Y Dược Cần Thơ, Chứng chỉ Nội tiết sinh sản',
                'date_of_birth' => '1979-09-26',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Chuyên khoa Cơ xương khớp (id: 6) - Bác sĩ 35-38
            [
                'id' => 30,
                'doctorId' => 35,
                'clinicId' => 1,
                'specializationId' => 6, // Cơ xương khớp
                'phone' => '0909000029',
                'photo' => 'doctor29.jpg',
                'bio' => 'Bác sĩ chuyên khoa cơ xương khớp, đặc biệt trong điều trị thoái hóa khớp gối và khớp háng. Có kinh nghiệm tiêm huyết tương giàu tiểu cầu.',
                'experience_years' => 8,
                'certification' => 'Bác sĩ chuyên khoa I Cơ xương khớp – Đại học Y Hà Nội, Chứng chỉ Tiêm khớp dưới hướng dẫn siêu âm',
                'date_of_birth' => '1984-06-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'doctorId' => 36,
                'clinicId' => 2,
                'specializationId' => 6, // Cơ xương khớp
                'phone' => '0909000030',
                'photo' => 'doctor30.jpg',
                'bio' => 'Chuyên gia về bệnh lý cột sống và đau thần kinh tọa. Từng tu nghiệp tại Đức về kỹ thuật điều trị không phẫu thuật.',
                'experience_years' => 12,
                'certification' => 'Thạc sĩ Cơ xương khớp – Đại học Y Dược TP.HCM, Chứng chỉ Cột sống học',
                'date_of_birth' => '1980-01-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'doctorId' => 37,
                'clinicId' => 3,
                'specializationId' => 6, // Cơ xương khớp
                'phone' => '0909000031',
                'photo' => 'doctor31.jpg',
                'bio' => 'Bác sĩ chuyên về bệnh tự miễn cơ xương khớp như viêm khớp dạng thấp, lupus. Có nhiều nghiên cứu về sinh học phân tử.',
                'experience_years' => 10,
                'certification' => 'Bác sĩ chuyên khoa II Cơ xương khớp – Đại học Y Dược Huế, Chứng chỉ Miễn dịch học lâm sàng',
                'date_of_birth' => '1982-03-19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'doctorId' => 38,
                'clinicId' => 4,
                'specializationId' => 6, // Cơ xương khớp
                'phone' => '0909000032',
                'photo' => 'doctor32.jpg',
                'bio' => 'Chuyên gia về chấn thương chỉnh hình và thể thao. Điều trị các chấn thương thể thao và phục hồi chức năng vận động.',
                'experience_years' => 9,
                'certification' => 'Bác sĩ chuyên khoa I Cơ xương khớp – Đại học Y Dược Cần Thơ, Chứng chỉ Chấn thương thể thao',
                'date_of_birth' => '1983-10-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Chuyên khoa Mắt (id: 7) - Bác sĩ 39-42
            [
                'id' => 34,
                'doctorId' => 39,
                'clinicId' => 5,
                'specializationId' => 7, // Mắt
                'phone' => '0909000033',
                'photo' => 'doctor33.jpg',
                'bio' => 'Bác sĩ nhãn khoa chuyên về phẫu thuật đục thủy tinh thể và tật khúc xạ. Đã thực hiện hơn 1000 ca mổ bằng công nghệ Phaco.',
                'experience_years' => 7,
                'certification' => 'Bác sĩ chuyên khoa I Mắt – Đại học Y Hà Nội, Chứng chỉ Phẫu thuật Phaco',
                'date_of_birth' => '1985-08-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'doctorId' => 40,
                'clinicId' => 1,
                'specializationId' => 7, // Mắt
                'phone' => '0909000034',
                'photo' => 'doctor34.jpg',
                'bio' => 'Chuyên gia về võng mạc và bệnh lý đáy mắt. Từng tu nghiệp tại Mỹ về kỹ thuật tiêm nội nhãn và laser võng mạc.',
                'experience_years' => 13,
                'certification' => 'Thạc sĩ Nhãn khoa – Đại học Y Dược TP.HCM, Chứng chỉ Bệnh lý võng mạc',
                'date_of_birth' => '1979-05-17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'doctorId' => 41,
                'clinicId' => 2,
                'specializationId' => 7, // Mắt
                'phone' => '0909000035',
                'photo' => 'doctor35.jpg',
                'bio' => 'Bác sĩ chuyên về glocom (thiên đầu thống) và nhãn áp. Có nhiều kinh nghiệm trong điều trị bảo tồn và phẫu thuật glocom.',
                'experience_years' => 11,
                'certification' => 'Bác sĩ chuyên khoa II Mắt – Đại học Y Dược Huế, Chứng chỉ Glocom học',
                'date_of_birth' => '1981-12-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'doctorId' => 42,
                'clinicId' => 3,
                'specializationId' => 7, // Mắt
                'phone' => '0909000036',
                'photo' => 'doctor36.jpg',
                'bio' => 'Chuyên gia về mắt trẻ em và lác mắt. Điều trị các tật khúc xạ ở trẻ em và phẫu thuật chỉnh lác.',
                'experience_years' => 9,
                'certification' => 'Bác sĩ chuyên khoa I Mắt – Đại học Y Dược Cần Thơ, Chứng chỉ Nhãn khoa nhi',
                'date_of_birth' => '1983-03-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Chuyên khoa Nha khoa (id: 8) - Bác sĩ 43-46
            [
                'id' => 38,
                'doctorId' => 43,
                'clinicId' => 4,
                'specializationId' => 8, // Nha khoa
                'phone' => '0909000037',
                'photo' => 'doctor37.jpg',
                'bio' => 'Bác sĩ nha khoa chuyên về chỉnh nha và niềng răng. Có kinh nghiệm với các hệ thống mắc cài hiện đại và Invisalign.',
                'experience_years' => 8,
                'certification' => 'Bác sĩ Răng Hàm Mặt – Đại học Y Hà Nội, Chứng chỉ Chỉnh nha',
                'date_of_birth' => '1984-07-19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'doctorId' => 44,
                'clinicId' => 5,
                'specializationId' => 8, // Nha khoa
                'phone' => '0909000038',
                'photo' => 'doctor38.jpg',
                'bio' => 'Chuyên gia về implant và phục hình răng. Từng tu nghiệp tại Thụy Sĩ về kỹ thuật cấy ghép implant nâng cao.',
                'experience_years' => 14,
                'certification' => 'Thạc sĩ Răng Hàm Mặt – Đại học Y Dược TP.HCM, Chứng chỉ Implant học',
                'date_of_birth' => '1978-11-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'doctorId' => 45,
                'clinicId' => 1,
                'specializationId' => 8, // Nha khoa
                'phone' => '0909000039',
                'photo' => 'doctor39.jpg',
                'bio' => 'Bác sĩ chuyên về nha khoa tổng quát và điều trị tủy. Sử dụng công nghệ vi phẫu trong điều trị nội nha phức tạp.',
                'experience_years' => 10,
                'certification' => 'Bác sĩ chuyên khoa I Răng Hàm Mặt – Đại học Y Dược Huế, Chứng chỉ Nội nha vi phẫu',
                'date_of_birth' => '1982-02-26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'doctorId' => 46,
                'clinicId' => 2,
                'specializationId' => 8, // Nha khoa
                'phone' => '0909000040',
                'photo' => 'doctor40.jpg',
                'bio' => 'Chuyên gia về nha chu và phẫu thuật răng miệng. Điều trị các bệnh về nướu và thực hiện phẫu thuật nha chu phức tạp.',
                'experience_years' => 12,
                'certification' => 'Bác sĩ chuyên khoa II Răng Hàm Mặt – Đại học Y Dược Cần Thơ, Chứng chỉ Nha chu học',
                'date_of_birth' => '1980-09-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
