<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExtraInfoSeeder extends Seeder
{
    public function run()
    {
        DB::table('extra_infos')->truncate();
        DB::table('extra_infos')->insert([
            [
                'id' => 9,
                'userId' => 2,
                'patientId' => 16,
                'historyBreath' => 'Không có tiền sử hô hấp nghiêm trọng',
                'placeId' => 1,
                'oldForms' => '[]',
                'sendForms' => '[]',
                'moreInfo' => 'Bệnh nhân dễ bị cảm lạnh',
                'blood_type' => 'O+',
                'height' => 170,
                'weight' => 65,
                'created_at' => '2025-11-28 13:49:34',
            ],
            [
                'id' => 10,
                'userId' => 3,
                'patientId' => 17,
                'historyBreath' => 'Đôi khi khó thở khi vận động',
                'placeId' => 4,
                'oldForms' => '[]',
                'sendForms' => '[]',
                'moreInfo' => 'Cần theo dõi huyết áp',
                'blood_type' => 'A+',
                'height' => 168,
                'weight' => 70,
                'created_at' => '2025-11-28 13:49:34',
            ],
            [
                'id' => 11,
                'userId' => 4,
                'patientId' => 18,
                'historyBreath' => 'Có tiền sử hen nhẹ',
                'placeId' => 5,
                'oldForms' => '[]',
                'sendForms' => '[]',
                'moreInfo' => 'Dị ứng phấn hoa mùa xuân',
                'blood_type' => 'B+',
                'height' => 160,
                'weight' => 55,
                'created_at' => '2025-11-28 13:49:34',
            ],
            [
                'id' => 12,
                'userId' => 5,
                'patientId' => 19,
                'historyBreath' => 'Khó thở nhẹ khi mệt',
                'placeId' => 2,
                'oldForms' => '[]',
                'sendForms' => '[]',
                'moreInfo' => 'Cần ăn uống hợp lý',
                'blood_type' => 'AB+',
                'height' => 172,
                'weight' => 78,
                'created_at' => '2025-11-28 13:49:34',
            ],
            [
                'id' => 13,
                'userId' => 6,
                'patientId' => 20,
                'historyBreath' => 'Không có triệu chứng hô hấp',
                'placeId' => 3,
                'oldForms' => '[]',
                'sendForms' => '[]',
                'moreInfo' => 'Theo dõi thể trạng cơ xương',
                'blood_type' => 'O-',
                'height' => 175,
                'weight' => 72,
                'created_at' => '2025-11-28 13:49:34',
            ],
            [
                'id' => 14,
                'userId' => 51,
                'patientId' => 21,
                'historyBreath' => 'Đôi khi ho về đêm',
                'placeId' => 5,
                'oldForms' => '[]',
                'sendForms' => '[]',
                'moreInfo' => 'Kiểm tra mắt định kỳ',
                'blood_type' => 'A-',
                'height' => 162,
                'weight' => 58,
                'created_at' => '2025-11-28 13:49:34',
            ],
            [
                'id' => 15,
                'userId' => 52,
                'patientId' => 22,
                'historyBreath' => 'Tiền sử viêm phổi năm 2020',
                'placeId' => 4,
                'oldForms' => '[]',
                'sendForms' => '[]',
                'moreInfo' => 'Cần chăm sóc răng miệng tốt',
                'blood_type' => 'B-',
                'height' => 169,
                'weight' => 74,
                'created_at' => '2025-11-28 13:49:34',
            ],
            [
                'id' => 16,
                'userId' => 53,
                'patientId' => 23,
                'historyBreath' => 'Không có vấn đề hô hấp',
                'placeId' => 2,
                'oldForms' => '[]',
                'sendForms' => '[]',
                'moreInfo' => 'Khám sản phụ khoa định kỳ',
                'blood_type' => 'AB-',
                'height' => 158,
                'weight' => 52,
                'created_at' => '2025-11-28 13:49:34',
            ],
        ]);
    }
}