<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostSeeder extends Seeder
{
    public function run()
    {
        DB::table('posts')->truncate();
        DB::table('posts')->insert([
            ['id' => 1, 'title' => '7 lời khuyên để có một trái tim khỏe mạnh', 'contentMarkdown' => 'Chuyên gia tim mạch chia sẻ các bí quyết đơn giản nhưng hiệu quả để bảo vệ sức khỏe tim mạch.', 'contentHTML' => '<p>Chuyên gia tim mạch chia sẻ các bí quyết đơn giản nhưng hiệu quả để bảo vệ sức khỏe tim mạch.</p>', 'writerId' => 1, 'confirmByDoctor' => 1, 'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDDQCUJw56m3H-xq82BPDJ3GMfLFGCooZ2p7-CoIHnWsc7NU1wxkQw3MZX6G_PkJiJvAM2LClpsIKJfBEwtoPsHKo7k_8iPsuKpg76jjeG98DlHN0MVWnq9zxvrMLKY0DxRM9ndLPOeTbm1Ji4SzD8BW33fCDvdUS8uwZariYuXtvMtLuswGLztLKfWctEfq6gwQO_V6rtX6uKGWIJOfLT6N2_fE2xuvSUgRoe14kCZdyTMXuKAD22Ay6vtfG-yEQB_JToe32Lj3Yc', 'created_at' => '2025-11-28 10:00:00'],
            ['id' => 2, 'title' => 'Chế độ ăn uống cân bằng cho người bận rộn', 'contentMarkdown' => 'Hướng dẫn duy trì chế độ ăn uống lành mạnh khi không có nhiều thời gian.', 'contentHTML' => '<p>Hướng dẫn duy trì chế độ ăn uống lành mạnh khi không có nhiều thời gian.</p>', 'writerId' => 1, 'confirmByDoctor' => 1, 'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCkwU4-0_27rDFiMV2iQM3yF5aDiXJr6GQcRwPitWem1OZQCpBe3WjU9sPO9a-skxmz3BJyBH-rwAMYILK2aey4fiiUPefiMBWaN6ZrXL8-l0Dj75mGsvjpotX9XvSN0sLZNt0FrGN1qAvJKPPTNamjqT5QDD74svnUihfsgotQRCj1mGxnWUNiA17R4PQTSiTlAPnSIhu-lT69WGNxbO9zvu6xgMOgogsARHeWxm_P1lKdyXJF3rHudJI0iWAbHvgvuSKxlpIdN9g', 'created_at' => '2025-11-28 10:00:00'],
            ['id' => 3, 'title' => 'Giảm căng thẳng và lo âu với 5 bài tập thở', 'contentMarkdown' => 'Các kỹ thuật thở đơn giản giúp bình tĩnh và cải thiện sức khỏe tinh thần.', 'contentHTML' => '<p>Các kỹ thuật thở đơn giản giúp bình tĩnh và cải thiện sức khỏe tinh thần.</p>', 'writerId' => 1, 'confirmByDoctor' => 1, 'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3pDA5-4UCVlO1Cwp_-THfHvDoT1uJOfgcqPxPRNPTaPO47DOYSGup-yDlywfPBI_DlIRffUj-sdb4n5M98U-p-KnjufrbU7u21qqdDyBhxH8zPm1pIh2gsDJQfGkr_VyXMdGHSJ-eb2Ve1ytu1FcyG311O3afDRc9RzcKgrUIBb25hg3dZwZojhzMAZif7IejaOkbnqAm5EqpnA7bL_eq0a5Qw5-_oGiMEEFMejdKDthzdhafofwDqySbYfMcDyQ33b6W85DI2Yk', 'created_at' => '2025-11-28 10:00:00'],
            ['id' => 4, 'title' => 'AI đang thay đổi ngành chẩn đoán hình ảnh như thế nào', 'contentMarkdown' => 'Trí tuệ nhân tạo mang lại những bước tiến vượt bậc trong phát hiện sớm và chẩn đoán bệnh.', 'contentHTML' => '<p>Trí tuệ nhân tạo mang lại những bước tiến vượt bậc trong phát hiện sớm và chẩn đoán bệnh.</p>', 'writerId' => 1, 'confirmByDoctor' => 1, 'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDFyr0wJZ_1_I6lvtRIRACwwvdrXBQKmSelRS7HoEcCxACNBIR_VobfJcqPcPyd-FuzGwI2P-un-msEufqFySqUr5pJt8hObDZhv8YRtrkAh7j0HshtvfTKVLOVEIf4RHPTugQ9IMolhXSZL5HR8XXh0mEa9RSX5I2_5B-TYtXYRjnOU5e5OPBON_R2ZdiOwBl14TklaJr5hHG-j3vSGnTzcLig8B-K9ZqdEces2btfv_cz5yrm0iWMPQHyXdnbcaSQLRwonvQxzLc', 'created_at' => '2025-11-28 10:00:00'],
            ['id' => 5, 'title' => 'Tầm quan trọng của giấc ngủ đối với sức khỏe', 'contentMarkdown' => 'Khám phá lý do tại sao giấc ngủ ngon là nền tảng cho cơ thể và tinh thần khỏe mạnh.', 'contentHTML' => '<p>Khám phá lý do tại sao giấc ngủ ngon là nền tảng cho cơ thể và tinh thần khỏe mạnh.</p>', 'writerId' => 1, 'confirmByDoctor' => 1, 'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDdatFsojk6832TSaQUsLQnJmcuCpp07aAwNUoIXMlzmdn3zMi_F4Nb81kSjAZZtDUtBA4UcSqmc-J6ZN4ZRad3JLJeLdz17eoQMEy3UHvXERtiLJYMCfceiVCw2grjWTaua5lnUcHg4CfOwJatweov2-tocj-Z2uhWNI6S6c5AXUlBBdgVklVTGoEGiOYZp-UmF0NZJULMKB0msDSFfor1L7X0D51ZDg9XxGimstUGc8X9c8VpkzmjfuzwD3O96mitxuJcFlu4UtQ', 'created_at' => '2025-11-28 10:00:00'],
            ['id' => 6, 'title' => '5 thói quen đơn giản giúp tăng cường hệ miễn dịch', 'contentMarkdown' => 'Xây dựng hàng rào bảo vệ cơ thể bằng những thay đổi nhỏ trong lối sống hàng ngày.', 'contentHTML' => '<p>Xây dựng hàng rào bảo vệ cơ thể bằng những thay đổi nhỏ trong lối sống hàng ngày.</p>', 'writerId' => 1, 'confirmByDoctor' => 1, 'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBEnEdXFq_s8I6aOX7ajXMWxRLkf1NstIIthBuhgsgxoS2AQ-WDRTeEGoUK6AMuSoRmmWrXn2ro0-e6GKBXVVo9XriHMIsU7kzgZT3M48z1GFd9v1q6rEAW6zOQ1kEqGwQ87KvqVg088F5BZcDJ5vDFdwCP-R26xlex0gTVmCrA5FBbLGmWr3KNa1pGqKCvGvkuZyTEqJXe7lyDEbDgarlDVJxNs_bpm7G1b_VYs4I0XcUnAwzM6mrCTbX7k1sjf7fuk8lHs2GeFA', 'created_at' => '2025-11-28 10:00:00'],
        ]);
    }
}