<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'iLoileDev',
                'email' => 'admin@gmail.com',
                'password' => '$2y$12$hrElLGLajA938uHMNa1V/.fWQKUuZYbM2ElSV44jLAeNQtWVyqWfi',
                'remember_token' => '5WpdBhN9JSukbwXpWvu7xsX3lLyX7JQw8a9LKdy3LYzfZvfITpavPAjUs4kZ',
                'address' => null,
                'phone' => null,
                'avatar' => 'https://media.istockphoto.com/id/1199037439/vi/vec-to/kh%C3%B3a-an-to%C3%A0n-v%C3%A0-h%C3%ACnh-%E1%BA%A3nh-bi%E1%BB%83u-t%C6%B0%E1%BB%A3ng-ch%E1%BB%AF-t%C6%B0%E1%BB%A3ng-h%C3%ACnh-ng%C6%B0%E1%BB%9Di-%C4%91%C3%A0n-%C3%B4ng-bi%E1%BB%83u-t%C6%B0%E1%BB%A3ng-kh%C3%B3a-v%C3%A0-ng%C6%B0%E1%BB%9Di.jpg?s=612x612&w=0&k=20&c=IXcwbWv_K1YlAQ3CdI0hotNjRFPgdFrOTFNW8_VI2vA=',
                'gender' => 'Nam',
                'roleId' => 1,
                'isActive' => 1,
                'created_at' => '2025-11-26 05:16:59',
                'updated_at' => '2025-11-26 05:16:59',
                'deleted_at' => null,
            ],
            // --- Doctors ---
            [
                'id' => 7,
                'name' => 'Dr. Trịnh Trần Phương Hướng',
                'email' => 'doctor1@gmail.com',
                'password' => '$2y$12$7H.TdCSEGpFFbiu70unl3.nthrElZSzzj0ucWeo0Vo5cewjczjRsC',
                'remember_token' => null,
                'address' => 'Bến Tre',
                'phone' => '0909123456',
                'avatar' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCkxmitPoFXpxvpuWGI_2HrlehwV-XKyJwlg73pQd1PVaQyg2r_G7zRxRCSOH1Cto51sKaQZmzRrp5y98OczTir5jkczGvLbtqF-XC1FtN5N8tJoS_tv9P6AtrXayMcfScy-5aW8R_g4AtylnmXXTrfpN7l3Ujq_USIa-pzxrwrD5c6WT1vnRBc5eqv0vyzOXB33UEATrQLpfCRVaoRF4gtErR8-Z1sGZ2AaZlk5Ng7dQQAXAYXVAVjyh0FBL16-aayJhaP4qXM3g',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => '2025-11-26 05:54:18',
                'updated_at' => '2025-11-26 05:54:18',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'Dr. Trần Mạnh Hùng',
                'email' => 'doctor2@gmail.com',
                'password' => '$2y$12$Wz4p2Bl58yXuJ.vj5q6F9.wcXzIc/DXds3z1TJVkEjJxuzaYnyFy6',
                'remember_token' => null,
                'address' => 'TP. Hồ Chí Minh',
                'phone' => '0912345678',
                'avatar' =>
'https://png.pngtree.com/png-vector/20250813/ourlarge/pngtree-smiling-male-doctor-in-white-coat-portrait-against-light-gray-background-png-image_16654591.png',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => '2025-11-26 12:31:35',
                'updated_at' => '2025-11-26 12:31:35',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'Dr. Phan Vân Tường',
                'email' => 'doctor3@gmail.com',
                'password' => '$2y$12$8N1Vh14KYGzw3e29Ueyzsu.kcvn2MqBfKwtXRArI2cw4/gdWiVKxi',
                'remember_token' => null,
                'address' => 'Vĩnh Long',
                'phone' => '0987654321',
                'avatar' =>
'https://png.pngtree.com/png-vector/20250105/ourlarge/pngtree-portrait-studio-isolated-cutout-closeup-shot-of-asian-professional-successful-female-png-image_15063485.png',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => '2025-11-26 12:31:35',
                'updated_at' => '2025-11-26 12:31:35',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'Dr. Nguyễn An',
                'email' => 'doctor4@gmail.com',
                'password' => '$2y$12$UbfFeA5GD1fwsMg.iOsCM.i6x0JDnPqaBpP.xThEUM37W2nJkdYru',
                'remember_token' => null,
                'address' => 'Trà Vinh',
                'phone' => '0909000004',
                'avatar' =>
'https://media.istockphoto.com/id/2207618864/photo/portrait-of-male-medical-professional-in-lab-coat-with-hands-in-pockets-standing-on-white.jpg?s=612x612&w=0&k=20&c=oIxLcIbVlAN0ZLRQ9fGaQoTNOUX19TcEQHiNmo6D_gY=',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => '2025-11-28 13:24:00',
                'updated_at' => '2025-11-28 13:24:00',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'Dr. Lê Bảo',
                'email' => 'doctor5@gmail.com',
                'password' => '$2y$12$mNgzmABZbr94CIq3wr6rze6qH8EbXM5PYVd0IbZs.kSAumeWP6MUu',
                'remember_token' => null,
                'address' => 'Bình Dương',
                'phone' => '0909000005',
                'avatar' =>
'https://media.istockphoto.com/id/1418258989/photo/professional-doctor-in-white-uniform-posing-on-camera-with-clipboard.jpg?s=612x612&w=0&k=20&c=jgyohIi6aFuX6kUdatVyg0ETzUlc-U4i-HGb-JMwFxs=',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => '2025-11-28 13:24:01',
                'updated_at' => '2025-11-28 13:24:01',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'Dr. Trần Cường',
                'email' => 'doctor6@gmail.com',
                'password' => '$2y$12$eGmZdyxjG.Arblabn5Xtl.qFi6eIE6Qf81xeGFKJLaIHjnlHklp2a',
                'remember_token' => null,
                'address' => 'Hải Phòng',
                'phone' => '0909000006',
                'avatar' =>
'https://media.istockphoto.com/id/1635982957/photo/happy-asian-man-doctor-and-arms-crossed-in-confidence-of-healthcare-consultant-at-the-office.jpg?s=612x612&w=0&k=20&c=h6afWku3v9XVNVtZ86zYn0nIH8lOw-3v4rdIIt_VwA8=',
                'gender' => 'Nam',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => '2025-11-28 13:24:01',
                'updated_at' => '2025-11-28 13:24:01',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'Dr. Phạm Di',
                'email' => 'doctor7@gmail.com',
                'password' => '$2y$12$ieLebNJ/2gnLjHh0uBqfiuCSv8J3WhdiYZCTOokL4NYcdzhTQgzOS',
                'remember_token' => null,
                'address' => 'Đà Nẵng',
                'phone' => '0909000007',
                'avatar' =>
'https://www.shutterstock.com/image-photo/portrait-caucasian-female-doctor-standing-600nw-2557673827.jpg',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => '2025-11-28 13:24:01',
                'updated_at' => '2025-11-28 13:24:01',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'Dr. Nguyễn Hạnh',
                'email' => 'doctor8@gmail.com',
                'password' => '$2y$12$hu6icHVTQWet84B.yCNYhulP9ikon3zol.3a5K7iN1grooQCiCBMq',
                'remember_token' => null,
                'address' => 'Cần Thơ',
                'phone' => '0909000008',
                'avatar' =>
'https://www.shutterstock.com/image-photo/portrait-happy-asian-female-doctor-260nw-2590900925.jpg',
                'gender' => 'Nữ',
                'roleId' => 2,
                'isActive' => 1,
                'created_at' => '2025-11-28 13:24:01',
                'updated_at' => '2025-11-28 13:24:01',
                'deleted_at' => null,
            ],




            //============== PATIENT ==============
            [
                'id' => 2,
                'name' => 'Nguyễn Vân Anh',
                'email' => 'patient1@gmail.com',
                'password' => '$2y$12$reW9JSP.q//DOboUhk2DbO2/Q37kyCCuA633BCUbmbF11Hu47RY62',
                'remember_token' => null,
                'address' => 'Cần Thơ',
                'phone' => '0909123456',
                'avatar' => 'https://i.pravatar.cc/300?img=2',
                'gender' => 'Nam',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-26 05:54:18',
                'updated_at' => '2025-11-26 05:54:18',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Nguyễn Nhật Minh ',
                'email' => 'patient2@gmail.com',
                'password' => '$2y$12$e0NRF3vHqi7kXfC8U6F4fOu5tVQp3dZVupvym6G5OjPqv.K6pq1rK',
                'remember_token' => null,
                'address' => 'Đà Nẵng',
                'phone' => '0912345678',
                'avatar' => 'https://i.pravatar.cc/300?img=3',
                'gender' => 'Nam',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-28 16:32:43',
                'updated_at' => '2025-11-28 16:32:43',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Thái Thị Mỹ ',
                'email' => 'patient3@gmail.com',
                'password' => '$2y$12$e0NRF3vHqi7kXfC8U6F4fOu5tVQp3dZVupvym6G5OjPqv.K6pq1rK',
                'remember_token' => null,
                'address' => 'Hà Nội',
                'phone' => '0987654321',
                'avatar' => 'https://i.pravatar.cc/300?img=4',
                'gender' => 'Nữ',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-28 16:32:43',
                'updated_at' => '2025-11-28 16:32:43',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Trần Thị Tuyết',
                'email' => 'patient4@gmail.com',
                'password' => '$2y$12$XXV9sxFJ9FHfa3GF8/M6M.cj29wGcneay2OB9hfBO5f1lj4x7mcEG',
                'remember_token' => null,
                'address' => 'Vĩnh Long',
                'phone' => '0909000001',
                'avatar' => 'https://i.pravatar.cc/300?img=5',
                'gender' => 'Nữ',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-26 12:31:36',
                'updated_at' => '2025-11-26 12:31:36',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'Trần Văn Toàn',
                'email' => 'patient5@gmail.com',
                'password' => '$2y$12$dVYM5pq5PJU.4ufJ48gaTOHf53AUNRlj2PEEve2NC/j8Zc5/yvJUa',
                'remember_token' => null,
                'address' => 'Đà Nẵng',
                'phone' => '0909000002',
                'avatar' => 'https://i.pravatar.cc/300?img=6',
                'gender' => 'Nam',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-26 12:31:36',
                'updated_at' => '2025-11-26 12:31:36',
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'name' => 'Trần Chấn Hào',
                'email' => 'patient10@gmail.com',
                'password' => '$2y$12$dVYM5pq5PJU.4ufJ48gaTOHf53AUNRlj2PEEve2NC/j8Zc5/yvJUa',
                'remember_token' => null,
                'address' => 'Đà Nẵng',
                'phone' => '0909000002',
                'avatar' => 'https://i.pravatar.cc/300?img=7',
                'gender' => 'Nam',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-26 12:31:36',
                'updated_at' => '2025-11-26 12:31:36',
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'name' => 'Nguyễn Ngọc',
                'email' => 'patient11@gmail.com',
                'password' => '$2y$12$dVYM5pq5PJU.4ufJ48gaTOHf53AUNRlj2PEEve2NC/j8Zc5/yvJUa',
                'remember_token' => null,
                'address' => 'Đà Nẵng',
                'phone' => '0909000002',
                'avatar' => 'https://i.pravatar.cc/300?img=8',
                'gender' => 'Nam',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-26 12:31:36',
                'updated_at' => '2025-11-26 12:31:36',
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'name' => 'Trần Văn Toàn',
                'email' => 'patient12@gmail.com',
                'password' => '$2y$12$dVYM5pq5PJU.4ufJ48gaTOHf53AUNRlj2PEEve2NC/j8Zc5/yvJUa',
                'remember_token' => null,
                'address' => 'Đà Nẵng',
                'phone' => '0909000002',
                'avatar' => 'https://i.pravatar.cc/300?img=9',
                'gender' => 'Nam',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-26 12:31:36',
                'updated_at' => '2025-11-26 12:31:36',
                'deleted_at' => null,
            ],
            [
                'id' => 51,
                'name' => 'Nguyễn Thị Lan',
                'email' => 'patient6@gmail.com',
                'password' => '$2y$12$dVYM5pq5PJU.4ufJ48gaTOHf53AUNRlj2PEEve2NC/j8Zc5/yvJUa',
                'remember_token' => null,
                'address' => 'Đà Nẵng',
                'phone' => '0909000002',
                'avatar' => 'https://i.pravatar.cc/300?img=10',
                'gender' => 'Nữ',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-26 12:31:36',
                'updated_at' => '2025-11-26 12:31:36',
                'deleted_at' => null,
            ],
            [
                'id' => 52,
                'name' => 'Phạm Văn Hùng',
                'email' => 'patient7@gmail.com',
                'password' => '$2y$12$dVYM5pq5PJU.4ufJ48gaTOHf53AUNRlj2PEEve2NC/j8Zc5/yvJUa',
                'remember_token' => null,
                'address' => 'Đà Nẵng',
                'phone' => '0909000002',
                'avatar' => 'https://i.pravatar.cc/300?img=11',
                'gender' => 'Nam',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-26 12:31:36',
                'updated_at' => '2025-11-26 12:31:36',
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'name' => 'Lê Thị Hoa',
                'email' => 'patient8@gmail.com',
                'password' => '$2y$12$dVYM5pq5PJU.4ufJ48gaTOHf53AUNRlj2PEEve2NC/j8Zc5/yvJUa',
                'remember_token' => null,
                'address' => 'Đà Nẵng',
                'phone' => '0909000002',
                'avatar' => 'https://i.pravatar.cc/300?img=12',
                'gender' => 'Nữ',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-26 12:31:36',
                'updated_at' => '2025-11-26 12:31:36',
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'name' => 'Trần Văn Hoa',
                'email' => 'patient9@gmail.com',
                'password' => '$2y$12$dVYM5pq5PJU.4ufJ48gaTOHf53AUNRlj2PEEve2NC/j8Zc5/yvJUa',
                'remember_token' => null,
                'address' => 'Đà Nẵng',
                'phone' => '0909000002',
                'avatar' => 'https://i.pravatar.cc/300?img=13',
                'gender' => 'Nữ',
                'roleId' => 3,
                'isActive' => 1,
                'created_at' => '2025-11-26 12:31:36',
                'updated_at' => '2025-11-26 12:31:36',
                'deleted_at' => null,
            ],
        ]);
    }
}
